import { DefaultSupplyProps } from './types';

const defaultSupplies: DefaultSupplyProps[] = [
  { category: 'Alimentos e Água', name: 'Comidas não perecíveis' },
  { category: 'Alimentos e Água', name: 'Água potável' },
  { category: 'Alimentos e Água', name: 'Fórmula infantil' },
  { category: 'Medicamentos', name: 'Remédios básicos' },
  { category: 'Medicamentos', name: 'Medicamentos prescritos' },
  { category: 'Medicamentos', name: 'Kits de primeiros socorros' },
  { category: 'Voluntariado', name: 'Turnos de manhã' },
  { category: 'Voluntariado', name: 'Turnos de tarde' },
  { category: 'Voluntariado', name: 'Turnos de noite' },
  { category: 'Higiene Pessoal', name: 'Papel higiênico' },
  { category: 'Higiene Pessoal', name: 'Pasta de dente' },
  { category: 'Higiene Pessoal', name: 'Escova de dentes' },
  { category: 'Higiene Pessoal', name: 'Sabonetes' },
  { category: 'Higiene Pessoal', name: 'Fraldas' },
  { category: 'Higiene Pessoal', name: 'Absorventes higiênicos' },
  { category: 'Acomodações e Descanso', name: 'Colchões' },
  { category: 'Acomodações e Descanso', name: 'Cobertores' },
  { category: 'Acomodações e Descanso', name: 'Lençóis' },
  { category: 'Itens Descartáveis', name: 'Pratos' },
  { category: 'Itens Descartáveis', name: 'Copos' },
  { category: 'Itens Descartáveis', name: 'Talheres' },
  { category: 'Itens Descartáveis', name: 'Sacos de lixo' },
  { category: 'Vestuário', name: 'Roupas para adultos' },
  { category: 'Vestuário', name: 'Roupas para crianças' },
  { category: 'Vestuário', name: 'Roupas íntimas' },
  { category: 'Vestuário', name: 'Roupas para frio' },
  { category: 'Equipamentos de Emergência', name: 'Cordas' },
  { category: 'Equipamentos de Emergência', name: 'Pás' },
  { category: 'Equipamentos de Emergência', name: 'Cadeiras (tipo de praia)' },
  { category: 'Equipamentos de Emergência', name: 'Lanternas' },
  { category: 'Veículos de Resgate e Transporte', name: 'Carros' },
  { category: 'Veículos de Resgate e Transporte', name: 'Caminhões' },
  { category: 'Veículos de Resgate e Transporte', name: 'Jetskis' },
  { category: 'Veículos de Resgate e Transporte', name: 'Barcos' },
  { category: 'Veículos de Resgate e Transporte', name: 'Helicópteros' },
  { category: 'Especialistas e Profissionais', name: 'Médicos' },
  { category: 'Especialistas e Profissionais', name: 'Veterinários' },
  { category: 'Especialistas e Profissionais', name: 'Psicólogos' },
  { category: 'Especialistas e Profissionais', name: 'Assistentes Sociais' },
  { category: 'Cuidados com Animais', name: 'Ração para animais' },
  { category: 'Cuidados com Animais', name: 'Medicamentos veterinários' },
  { category: 'Cuidados com Animais', name: 'Leitos para animais' },
  { category: 'Cuidados com Animais', name: 'Coleiras' },
  { category: 'Material de Limpeza', name: 'Vassouras' },
  {
    category: 'Material de Limpeza',
    name: 'Produtos de desinfecção (cloro, álcool)',
  },
];

export { defaultSupplies };
